# Generated by Django 2.2.1 on 2019-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FileField(upload_to='model')),
                ('illumination', models.FloatField(default=1)),
                ('h', models.FloatField(default=-10)),
                ('h2o', models.FloatField(default=-10)),
                ('pi', models.FloatField(default=-10)),
                ('nh4', models.FloatField(default=-10)),
                ('no3', models.FloatField(default=-10)),
                ('so4', models.FloatField(default=-10)),
                ('o2', models.FloatField(default=-10)),
                ('ac', models.FloatField(default=0)),
                ('hash_str', models.TextField(null=True)),
                ('filetxt', models.TextField(null=True)),
            ],
        ),
    ]
