# Generated by Django 2.2.1 on 2019-06-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FileField(upload_to='cycle')),
                ('hash_str', models.TextField(null=True)),
                ('cycle_value', models.TextField(null=True)),
            ],
        ),
    ]
