# Generated by Django 2.2.1 on 2019-06-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_cycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='cycle_value',
            new_name='value',
        ),
    ]
