# Generated by Django 2.2.1 on 2019-06-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190629_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='value',
        ),
    ]
