# Generated by Django 2.2.1 on 2019-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_cycle_cycle_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.TextField(null=True)),
                ('value', models.TextField(null=True)),
            ],
        ),
    ]
