# Generated by Django 2.2.1 on 2019-07-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactions',
            name='id',
        ),
        migrations.AddField(
            model_name='reactions',
            name='hash_str',
            field=models.TextField(default='1', primary_key=True, serialize=False),
        ),
    ]
