# Generated by Django 2.2.1 on 2019-07-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190709_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reactions',
        ),
    ]
