# Generated by Django 2.2.1 on 2019-07-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_reactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reactions',
        ),
    ]
