# Generated by Django 2.2.1 on 2019-08-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='cycle_value',
        ),
    ]
